package com.urlshortner.Utitlities;

public class MessageData {

    public static String getMessageBodyForOTP(String otp) {
        return "<!DOCTYPE html>\r\n"
                + "<html>\r\n"
                + "<head>\r\n"
                + "    <meta charset=\"UTF-8\">\r\n"
                + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
                + "    <title>OTP Verification - URL Shortener</title>\r\n"
                + "    <style>\r\n"
                + "        body {\r\n"
                + "            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n"
                + "            background-color: #f2f2f2;\r\n"
                + "            padding: 20px;\r\n"
                + "            display: flex;\r\n"
                + "            justify-content: center;\r\n"
                + "            align-items: center;\r\n"
                + "            height: 100vh;\r\n"
                + "        }\r\n"
                + "        .email-container {\r\n"
                + "            max-width: 600px;\r\n"
                + "            background-color: #ffffff;\r\n"
                + "            padding: 30px;\r\n"
                + "            border-radius: 10px;\r\n"
                + "            box-shadow: 0 4px 8px rgba(0,0,0,0.1);\r\n"
                + "            text-align: center;\r\n"
                + "        }\r\n"
                + "        .email-container h2 {\r\n"
                + "            color: #2c3e50;\r\n"
                + "        }\r\n"
                + "        .otp-code {\r\n"
                + "            font-size: 28px;\r\n"
                + "            font-weight: bold;\r\n"
                + "            color: #007bff;\r\n"
                + "            margin: 20px 0;\r\n"
                + "        }\r\n"
                + "        .footer {\r\n"
                + "            font-size: 13px;\r\n"
                + "            color: #888;\r\n"
                + "            margin-top: 30px;\r\n"
                + "        }\r\n"
                + "        .app-name {\r\n"
                + "            font-weight: bold;\r\n"
                + "            color: #16a085;\r\n"
                + "        }\r\n"
                + "    </style>\r\n"
                + "</head>\r\n"
                + "<body>\r\n"
                + "    <div class=\"email-container\">\r\n"
                + "        <h2>Verify Your Email Address</h2>\r\n"
                + "        <p>Thank you for using <span class=\"app-name\">URL Shortener</span>!</p>\r\n"
                + "        <p>Use the OTP below to verify your email address:</p>\r\n"
                + "        <p class=\"otp-code\">" + otp + "</p>\r\n"
                + "        <p>This OTP is valid for a short time. Please do not share it with anyone.</p>\r\n"
                + "        <p class=\"footer\">If you didn’t request this, please ignore this email or contact our support team.</p>\r\n"
                + "    </div>\r\n"
                + "</body>\r\n"
                + "</html>";
    }

    public static String getExpiryNotificationMessageBody(String linkCode, String formattedExpiry) {
        return "<!DOCTYPE html>\r\n"
                + "<html>\r\n"
                + "<head>\r\n"
                + "    <meta charset=\"UTF-8\">\r\n"
                + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
                + "    <title>Link Expiry Alert - URL Shortener</title>\r\n"
                + "    <style>\r\n"
                + "        body {\r\n"
                + "            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n"
                + "            background-color: #f8f9fa;\r\n"
                + "            padding: 20px;\r\n"
                + "            display: flex;\r\n"
                + "            justify-content: center;\r\n"
                + "            align-items: center;\r\n"
                + "            height: 100vh;\r\n"
                + "        }\r\n"
                + "        .email-container {\r\n"
                + "            max-width: 600px;\r\n"
                + "            background-color: #ffffff;\r\n"
                + "            padding: 30px;\r\n"
                + "            border-radius: 10px;\r\n"
                + "            box-shadow: 0 4px 10px rgba(0,0,0,0.1);\r\n"
                + "            text-align: center;\r\n"
                + "        }\r\n"
                + "        h2 {\r\n"
                + "            color: #e74c3c;\r\n"
                + "        }\r\n"
                + "        .link-code {\r\n"
                + "            font-size: 24px;\r\n"
                + "            font-weight: bold;\r\n"
                + "            color: #2c3e50;\r\n"
                + "            margin: 15px 0;\r\n"
                + "        }\r\n"
                + "        .expiry-time {\r\n"
                + "            font-size: 18px;\r\n"
                + "            color: #555;\r\n"
                + "            margin: 10px 0 30px;\r\n"
                + "        }\r\n"
                + "        .footer {\r\n"
                + "            font-size: 13px;\r\n"
                + "            color: #888;\r\n"
                + "        }\r\n"
                + "        .app-name {\r\n"
                + "            font-weight: bold;\r\n"
                + "            color: #16a085;\r\n"
                + "        }\r\n"
                + "    </style>\r\n"
                + "</head>\r\n"
                + "<body>\r\n"
                + "    <div class=\"email-container\">\r\n"
                + "        <h2>Link Expiry Reminder</h2>\r\n"
                + "        <p>Your short link <span class=\"link-code\">" + linkCode
                + "</span> is about to expire.</p>\r\n"
                + "        <p class=\"expiry-time\">Expiry Date: <b>" + formattedExpiry + "</b></p>\r\n"
                + "        <p>After this time, the link will no longer be accessible.</p>\r\n"
                + "        <p class=\"footer\">If you have questions, contact <a href='http://localhost:5173/'><span class=\"app-name\">ShortLink</span></a> support.</p>\r\n"
                + "    </div>\r\n"
                + "</body>\r\n"
                + "</html>";
    }
}
